### ISSUE TITLE
Intermittent crash on removing first item in a collection

### ISSUE THREAD

**Issue by ssokolow** [BestImageViewer/geeqie#1148]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Geeqie 2.1 GTK3
```

(More specifically, Flatpak [commit ID](https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading) `b9404f99e3213137727341c40d13ce5da313915acdf025dcb1a3b18edebacded`)

### OS / DISTRIBUTION

```
ssokolow@monolith ~ % lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
ssokolow@monolith ~ % flatpak --version
Flatpak 1.14.4
```

### SUMMARY
Geeqie sometimes crashes when I hit the <kbd>Delete</kbd> key on the first item in a collection. It seems to happen more readily with bigger collections but I haven't tested that in a statically rigorous manner.

It also seems I can reliably work around it by dragging the image into another position before hitting <kbd>Delete</kbd>.

Here's what `flatpak run --devel --command=gdb org.geeqie.Geeqie /app/bin/geeqie` has to say about it:

```
Thread 1 "geeqie" received signal SIGSEGV, Segmentation fault.
0x00007ffff6ef98f1 in g_value_object_collect_value () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt full
#0  0x00007ffff6ef98f1 in g_value_object_collect_value () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff6efd2ce in g_object_set_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff6efdeaf in g_object_set () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x00005555555e7fc4 in  ()
#4  0x00007ffff750f71e in apply_cell_attributes () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007ffff6f8c262 in g_hash_table_foreach () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff750f5b1 in gtk_cell_area_real_apply_attributes () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007ffff7515040 in gtk_cell_area_box_apply_attributes () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff74bf516 in _gtk_marshal_VOID__OBJECT_BOXED_BOOLEAN_BOOLEANv () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x00007ffff6ef465a in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6f0f53f in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6f0f743 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff751147e in gtk_cell_area_apply_attributes () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007ffff784d91d in set_cell_data () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007ffff784f79d in _gtk_tree_view_accessible_changed () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007ffff776ccdf in gtk_tree_view_row_changed () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#16 0x00007ffff6ef4442 in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007ffff6f085c8 in signal_emit_unlocked_R.isra.0 () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6f0f575 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6f0f743 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff762db58 in gtk_list_store_set_valist () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#21 0x00007ffff762dc1a in gtk_list_store_set () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#22 0x00005555555eab4e in  ()
#23 0x00007ffff6f9fd49 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff6fa02a8 in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff6fa058f in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff7631995 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#27 0x00005555555cddaa in  ()
#28 0x00007ffff641354a in __libc_start_call_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#29 0x00007ffff641360b in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#30 0x00005555555cf5a5 in  ()
```

### STEPS TO REPRODUCE
It appears to be some kind of memory-corruption bug and I haven't got a deterministic reproducer, because it sometimes takes several tries to crash Geeqie.

1. Open up a new collection
2. Drag-and-drop a bunch of images into it
3. Delete the first image
4. Repeat until Geeqie crashes (sometimes it happens first try, sometimes not), adding more images if necessary

**Comment by caclark** [comment]
OK. The bug is reproducible - in fact, on my system, it always crashes.
