### ISSUE TITLE
Geeqie doesn't catch exiv2 exceptions

### ISSUE THREAD

**Issue by tomaszg7** [BestImageViewer/geeqie#1181]
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
current HEAD

### SUMMARY
I have some problematic photo which causes Geeqie to crash. Attaching Geeqie output and backtrace. Tested with exiv2-0.28.0. 

The file in question is some test image I downloaded from here: http://www.normankoren.com/Tutorials/Lenstarg_25_7086p_15g_25is.png

It causes also `exiv2` standalone binary to throw, so the problem is probably their, but Geeqie should catch the exception and behave nicely.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  Overflow in Exiv2::DataBuf::c_data
Geeqie fatal error
Signal: Abort
Code: Invalid permissions
Address: 0x000003ea00007f55
geeqie(+0xdc3c5)[0x5593e84d63c5]
/lib64/libc.so.6(+0x38a00)[0x7ff850583a00]
/lib64/libc.so.6(+0x8868c)[0x7ff8505d368c]
/lib64/libc.so.6(gsignal+0x12)[0x7ff850583952]
/lib64/libc.so.6(abort+0xd3)[0x7ff85056d4b2]
/usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6(+0x9d98f)[0x7ff85089d98f]
/usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6(+0xa95b6)[0x7ff8508a95b6]
/usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6(+0xa9621)[0x7ff8508a9621]
/usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6(+0xa9882)[0x7ff8508a9882]
/usr/lib64/libexiv2.so.28(+0x104997)[0x7ff850f04997]
/usr/lib64/libexiv2.so.28(+0x1a1a95)[0x7ff850fa1a95]
/usr/lib64/libexiv2.so.28(+0x1a2fae)[0x7ff850fa2fae]
/usr/lib64/libexiv2.so.28(_ZN5Exiv28PngImage12readMetadataEv+0x1ee)[0x7ff85106aa7e]
geeqie(+0xa7e7b)[0x5593e84a1e7b]
geeqie(+0xa8651)[0x5593e84a2651]
geeqie(+0xa6121)[0x5593e84a0121]
geeqie(+0xa4069)[0x5593e849e069]
geeqie(+0xb9a8c)[0x5593e84b3a8c]
geeqie(+0xbabcf)[0x5593e84b4bcf]
geeqie(+0x11879e)[0x5593e851279e]
geeqie(+0x119067)[0x5593e8513067]
geeqie(+0x119aa7)[0x5593e8513aa7]
geeqie(+0x1448dc)[0x5593e853e8dc]
geeqie(+0x146668)[0x5593e8540668]
geeqie(+0x14ea2b)[0x5593e8548a2b]
geeqie(+0x14ecca)[0x5593e8548cca]
geeqie(+0x14dc62)[0x5593e8547c62]
geeqie(+0xc908c)[0x5593e84c308c]
geeqie(+0xcde11)[0x5593e84c7e11]
geeqie(+0xffbef)[0x5593e84f9bef]
geeqie(+0xfbe23)[0x5593e84f5e23]
/usr/lib64/libglib-2.0.so.0(+0x5ef04)[0x7ff85178df04]
/usr/lib64/libglib-2.0.so.0(g_markup_parse_context_parse+0x12ef)[0x7ff85178f45f]
geeqie(+0x10444a)[0x5593e84fe44a]
geeqie(+0x1044b0)[0x5593e84fe4b0]
geeqie(+0xe56a4)[0x5593e84df6a4]
geeqie(+0x73a2c)[0x5593e846da2c]
/lib64/libc.so.6(+0x238ca)[0x7ff85056e8ca]
/lib64/libc.so.6(__libc_start_main+0x85)[0x7ff85056e985]
geeqie(+0x74961)[0x5593e846e961]
```

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  Overflow in Exiv2::DataBuf::c_data

Thread 1 "geeqie" received signal SIGABRT, Aborted.
0x00007ffff5fd368c in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5fd368c in  () at /lib64/libc.so.6
#1  0x00007ffff5f83952 in raise () at /lib64/libc.so.6
#2  0x00007ffff5f6d4b2 in abort () at /lib64/libc.so.6
#3  0x00007ffff629d98f in  ()
    at /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
#4  0x00007ffff62a95b6 in  ()
    at /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
#5  0x00007ffff62a9621 in  ()
    at /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
#6  0x00007ffff62a9882 in  ()
    at /usr/lib/gcc/x86_64-pc-linux-gnu/12/libstdc++.so.6
#7  0x00007ffff6904997 in  () at /usr/lib64/libexiv2.so.28
#8  0x00007ffff69a1a95 in  () at /usr/lib64/libexiv2.so.28
#9  0x00007ffff69a2fae in  () at /usr/lib64/libexiv2.so.28
#10 0x00007ffff6a6aa7e in Exiv2::PngImage::readMetadata() ()
    at /usr/lib64/libexiv2.so.28
#11 0x00005555555fbe7b in ExifDataOriginal::ExifDataOriginal(char*)
    ()
#12 0x00005555555fc651 in ExifDataProcessed::ExifDataProcessed(char*, char*, _GHashTable*) ()
#13 0x00005555555fa121 in exif_read(char*, char*, _GHashTable*) ()
#14 0x00005555555f8069 in exif_read_fd(FileData*) ()
#15 0x00005555555fde18 in read_exif_time_data(FileData*) [clone .part.0] ()
#16 0x0000555555699088 in vf_read_metadata_in_idle_cb(void*) ()
#17 0x00007ffff718c50e in g_main_context_dispatch ()
    at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff718c8e8 in  () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff718cb9f in g_main_loop_run ()
    at /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff77fe16d in gtk_main () at /usr/lib64/libgtk-3.so.0
#21 0x00005555555c748e in main ()
```

**Comment by qarkai** [comment]
Can't reproduce with this image as of commit ec8abe313df02222d8f3bc69b08d79a7a5bcd5fd.

@caclark is this issue could be closed?
