### ISSUE TITLE
geeqie crashes on invalid filename encoding

### ISSUE THREAD

**Issue by mowgli** [BestImageViewer/geeqie#169]
Geeqie 1.0 core dumps when opening a directory with non-utf8 filenames. It generates traceback like that:

\(gdb\) bt
\#0  0x0000000803800f34 in strxfrm \(\) from /lib/libc.so.7
\#1  0x0000000802c604d8 in g\_utf8\_collate\_key \(\) from /usr/local/lib/libglib-2.0.so.0
\#2  0x000000000045ee62 in file\_data\_set\_collate\_keys \(fd=0x806cf9240\) at filedata.c:238
\#3  0x000000000045f14d in file\_data\_set\_path \(fd=0x806cf9240, path=0x806cf8310 "/home/novel/TRIAGRUTRIKA - �.�.�.���߿� \(2011\)"\)
at filedata.c:301
\#4  0x000000000045f71c in file\_data\_new \(path\_utf8=0x806cf8310 "/home/novel/TRIAGRUTRIKA - �.�.�.���߿� \(2011\)", st=0x7fffffffda50,
check\_sidecars=0, basename\_hash=0x0\) at filedata.c:441
\#5  0x000000000045fb38 in file\_data\_new\_local \(path=0x806aa69c0 "/home/novel/TRIAGRUTRIKA - �.�.�.���߿� \(2011\)", st=0x7fffffffda50,
check\_sidecars=0, basename\_hash=0x0\) at filedata.c:589
\#6  0x0000000000460d13 in filelist\_read\_real \(dir\_fd=0x806c80ac0, files=0x0, dirs=0x806b77e08, follow\_symlinks=1\) at filedata.c:1073
\#7  0x0000000000460e4a in filelist\_read \(dir\_fd=0x806c80ac0, files=0x0, dirs=0x806b77e08\) at filedata.c:1107
\#8  0x00000000004d6d0c in vdlist\_populate \(vd=0x806a5a900, clear=1\) at view\_dir\_list.c:154
\#9  0x00000000004d735d in vdlist\_set\_fd \(vd=0x806a5a900, dir\_fd=0x806c80ac0\) at view\_dir\_list.c:320
\#10 0x00000000004d4729 in vd\_set\_fd \(vd=0x806a5a900, dir\_fd=0x806c80ac0\) at view\_dir.c:159
\#11 0x0000000000478051 in layout\_sync\_path \(lw=0x806a9d800\) at layout.c:843
\#12 0x000000000047831d in layout\_set\_fd \(lw=0x806a9d800, fd=0x806c80ac0\) at layout.c:914
\#13 0x00000000004780ca in layout\_set\_path \(lw=0x806a9d800, path=0x806b35380 "/home/novel"\) at layout.c:855
\#14 0x000000000047c382 in layout\_new\_from\_config \(attribute\_names=0x7fffffffe070, attribute\_values=0x7fffffffdf50, use\_commandline=1\)
at layout.c:2426
\#15 0x00000000004bf4e4 in options\_parse\_toplevel \(parser\_data=0x806aa9c70, context=0x806a8a740, element\_name=0x806b1ed00 "layout",
attribute\_names=0x7fffffffe070, attribute\_values=0x7fffffffdf50, data=0x0, error=0x7fffffffe1a0\) at rcfile.c:1102
\#16 0x00000000004bf700 in start\_element \(context=0x806a8a740, element\_name=0x806b1ed00 "layout", attribute\_names=0x7fffffffe070,
attribute\_values=0x7fffffffdf50, user\_data=0x806aa9c70, error=0x7fffffffe1a0\) at rcfile.c:1167
\#17 0x0000000802c3636a in g\_markup\_collect\_attributes \(\) from /usr/local/lib/libglib-2.0.so.0
\#18 0x0000000802c370aa in g\_markup\_parse\_context\_parse \(\) from /usr/local/lib/libglib-2.0.so.0
\#19 0x00000000004bf861 in load\_config\_from\_buf \(
buf=0x806b2c000 "&lt;\!--\n", '\#' &lt;repeats 70 times&gt;, "\n\#", ' ' &lt;repeats 25 times&gt;, "Geeqie config file      version 1.0        \#\n", '\#' &lt;repeats 53 times&gt;..., size=13060, startup=1\) at rcfile.c:1212
\#20 0x00000000004bf929 in load\_config\_from\_file \(utf8\_path=0x806aa6980 "/home/novel/.config/geeqie/geeqierc.xml", startup=1\)
at rcfile.c:1234
\#21 0x000000000048f38d in load\_options \(options=0x806a69c00\) at options.c:258
\#22 0x000000000048854e in main \(argc=2, argv=0x7fffffffe410\) at main.c:824
\(gdb\)

It seems to happen because g\_utf8\_collate\_key\(\) always expects a valid UTF-8. In the attached diff I check if the file name if a valid UTF-8 string, if it's not convert it using g\_filename\_display\_name\(\). It fixes a problem for me.

Reported by: n0vel

**Comment by mowgli** [comment]
Ok, seems to be fixed. Closing.
